name: Auto-Merge Dependabot Minor Updates

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2

      - name: Enable auto-merge for minor updates
        if: steps.metadata.outputs.update-type == 'minor'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          merge-method: squash
