name: (📡) Auto-Merge Dependabot Minor Updates

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Print github.actor
        run: echo "Actor is ${{ github.actor }}"

        #    uses: sitepark/github-project-workflow/.github/workflows/dependabot-automerge-minor.yml@main
