name: (📡) Deploy Snapshot

on:
  push:
    branches:    
    - 'main'
  workflow_dispatch:

jobs:
  deploy:
    uses: sitepark/github-project-workflow/actions/type/maven/deploy-snapshot.yml@feat/factor-structure
    secrets:
      MVN_REPO_SERVER_USERNAME: ${{ secrets.MVN_REPO_SERVER_USERNAME }}
      MVN_REPO_SERVER_PASSWORD: ${{ secrets.MVN_REPO_SERVER_PASSWORD }}
      MVN_REPO_SERVER_ID: ${{ secrets.MVN_REPO_SERVER_ID }}
      MVN_REPO_SERVER_SNAPSHOT_URL: ${{ secrets.MVN_REPO_SERVER_SNAPSHOT_URL }}

