name: (📡) Publish Release

on:
   release:
      types: [published]

jobs:
  publish-release:
    uses: sitepark/github-project-workflow/.github/workflows/actions/type/maven/publish-release.yml@feat/factor-structure

