name: (📡) Verify

on:
  push:
    branches-ignore:
    - 'main'
    - 'dependabot/**'
  pull_request:
    branches-ignore:
    - 'main'
  workflow_dispatch:

jobs:
  verify:
    uses: sitepark/github-project-workflow/actions/type/maven/verify.yml@feat/factor-structure

